version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - EMAIL_PASSWORD=your_app_password
      - SENDER_EMAIL=your_email@gmail.com
    restart: unless-stopped
    volumes:
      - ./backend:/app
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped